version: "3"
services:

  web-artist:
    image: dolphinevents/artist-service:0.1.1
    ports:
      - "8082:8080"
    volumes:
      - ${PWD}/application-artist.properties:/opt/artist-service/application.properties
    restart: always
  
  artist-database:
    image: mysql:8
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=artist-database
      - MYSQL_PASSWORD=artistdatabase
      - MYSQL_DATABASE=artist-database

  web-events:
    image: dolphinevents/events-service:postgresql_latest
    ports:
      - "8083:8080"
    restart: always
    volumes:
      - ${PWD}/application-events.properties:/opt/events-service/application.properties  

  events-database:
    image: postgres:latest
    ports: 
      - "5433:5432"
    volumes:
      - ${PWD}/events.sql:/docker-entrypoint-initdb.d/events.sql
    environment:
      - POSTGRES_PASSWORD=password

  web-company:
    image: dolphinevents/company-service:0.1.1
    ports: 
      - "8084:8080"
    restart: always
    volumes:
      - ${PWD}/application-company.properties:/opt/company-service/application.properties

  company-database:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_DATABASE=company-database
      - MYSQL_USER=company-database
      - MYSQL_PASSWORD=companydatabase

  web-user:
    image: dolphinevents/user-service:0.2.1
    ports: 
      - "8085:8080"
    restart: always
    volumes:
      - ${PWD}/application-user.properties:/opt/user-service/application.properties

  user-database:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - ${PWD}/user.sql:/docker-entrypoint-initdb.d/user.sql
    environment:
      - POSTGRES_PASSWORD=password

  # gateway:
  #   image: nginx
  #   ports:
  #     - 8081:8080
  #   volumes: 
  #     - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
  #   restart: always
